name: CI/CD - Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout source
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Get short SHA for tagging
      - name: Set short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      # Build and push Docker image
      - name: Build & Push Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-flask-app:${{ steps.vars.outputs.sha_short }} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/my-flask-app:${{ steps.vars.outputs.sha_short }} ${{ secrets.DOCKERHUB_USERNAME }}/my-flask-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-flask-app:${{ steps.vars.outputs.sha_short }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-flask-app:latest

      # Deploy on remote server
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-flask-app:latest
            docker stop flask-app || true
            docker rm flask-app || true
            docker run -d --name flask-app -p 80:5000 ${{ secrets.DOCKERHUB_USERNAME }}/my-flask-app:latest
